apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: opendatahub
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: okd-community-operators
  sourceNamespace: openshift-marketplace
